# Generated by Django 4.1 on 2022-09-06 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noteapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteapp',
            name='generated_by',
        ),
        migrations.AddField(
            model_name='noteapp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
