# Generated by Django 4.1 on 2022-09-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_rename_todo_id_todolist_todoid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='lists',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
    ]
