# Generated by Django 4.0 on 2022-10-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_remove_todolist_lists_remove_todolist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='todoid',
        ),
        migrations.AddField(
            model_name='todo',
            name='lists',
            field=models.ManyToManyField(to='taskapp.TodoList'),
        ),
    ]
