# Generated by Django 4.1 on 2022-09-06 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plannerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannerapp',
            name='generated_by',
        ),
        migrations.AddField(
            model_name='plannerapp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
